# This action continuously checks all pushes and Pull requests
# for validity, integrity and bugs in datafiles.
# For details, visit https://github.com/BSData/check-datafiles
name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: BSData/check-datafiles@v1
      id: check

    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ${{ steps.check.outputs.staging-path }}
